# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Builds and exports project to Firebase App Distribution Console"
  lane :build_and_export do
    increment_version_number(
      version_number: "1.1"
    )

    gym(
      scheme: "CatsAndModules",
      workspace: "CatsAndModules.xcworkspace",
      destination: "generic/platform=iOS",
      export_method: "development",
      output_directory: "./output",
      export_options: {
        provisioningProfiles: {
          "ua.edu.ukma.derkach.CatsAndModules": "Kyrylo Derkach"
        }
      }
    )
    
    firebase_app_distribution(
      firebase_cli_token: "1//0c1sDmpByCA24CgYIARAAGAwSNwF-L9IrUO2eD5dw1k0kF8AeGtGM-mDRV24pofv5FmFhUztZOBfJlLY2ONfupu7qvWSqZY0qMiI",
      app: "1:301341426344:ios:4376cec4c159c018e8f89d",
      release_notes: "Fastlane third export raising version number for recording",
      testers: "o.frankiv@ukma.edu.ua"
    )
  end

  def screenshot_name(device, language, screen)
    "KyryloDerkach_#{screen}_#{device}_#{language}.png"
  end

  desc "Takes screenshots of application"
  lane :take_screenshots do
    fastlane snapshot
  end

end
